

## Numpy

In [2]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(5,)

In [6]:
array1.ndim

1

In [7]:
array2=np.array([[1,2,3,4,5],[11,22,33,44,55]])

In [8]:
array2.shape

(2, 5)

In [9]:
array2.ndim

2

In [11]:
array2=np.array([[1,2,3,4,5],[11,22,33,44,55]],dtype = float)

In [12]:
array2

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 22., 33., 44., 55.]])

In [13]:
array_reshape = array2.reshape(5,2)

In [14]:
array_reshape.shape

(5, 2)

In [16]:
array_reshape

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 11.],
       [22., 33.],
       [44., 55.]])

In [17]:
array_zero = np.zeros(8)

In [18]:
array_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones([3,3])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
np.ones([3,3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

## Creating an array with existing data

In [33]:
x1= ([3,5],[5,4],[6,7])
a1 = np.asarray(x1, dtype=float)

In [25]:
type(x1)

tuple

In [34]:
a1

array([[3., 5.],
       [5., 4.],
       [6., 7.]])

## Array from numerical ranges

In [35]:
a1= np.arange(0,20,3)

In [36]:
a1

array([ 0,  3,  6,  9, 12, 15, 18])

In [37]:
a1 = np.linspace(10,20,5)

In [38]:
a1

array([10. , 12.5, 15. , 17.5, 20. ])

## Slicing

In [40]:
list1 = np.arange(10)
array1 = slice(2,9,2)
list1[array1]

array([2, 4, 6, 8])

In [41]:
list1 = np.arange(10)
array1 = list1[2:9:2]
list1[array1]

array([2, 4, 6, 8])

## Integer indexing

In [42]:
a =np.array([[1,2],[3,4],[5,6]])
b = a[[0,1,2],[0,1,0]]

In [43]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
print(b)

[1 4 5]


In [45]:
a =np.array([[1,2,1],[3,4,1],[5,6,1],[7,8,1]])

In [46]:
a

array([[1, 2, 1],
       [3, 4, 1],
       [5, 6, 1],
       [7, 8, 1]])

In [47]:
a[1:4 ,1:3]

array([[4, 1],
       [6, 1],
       [8, 1]])

In [48]:
a[1: , 1:]

array([[4, 1],
       [6, 1],
       [8, 1]])

In [50]:
a = np.array([1,5,np.nan,8,np.nan,52,65,np.nan])

In [51]:
a

array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [52]:
a[~np.isnan(a)]

array([ 1.,  5.,  8., 52., 65.])

In [53]:
a[np.isnan(a)]

array([nan, nan, nan])

In [54]:
## tilde is opposite to nan function

NameError: name 'np' is not defined

In [11]:
a =np.array([[1,2,3],[4,5,6]])

In [12]:
b=np.array([[4,5,6],[7,8,9]])

In [13]:
a * b

array([[ 4, 10, 18],
       [28, 40, 54]])

## broadcasting

In [ ]:
a =np.array([1,2,3])

In [9]:
b=5

In [10]:
a * b

array([ 5, 10, 15])

In [14]:
a = np.array

In [16]:
a = np.array([[1,2,3],[4,5,6]])
b =5
a*b

array([[ 5, 10, 15],
       [20, 25, 30]])

In [17]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
a * b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [18]:
z = a*b

In [20]:
z.T #Transpose

array([[ 1,  4],
       [ 4, 10],
       [ 9, 18]])

In [21]:
array1 = np.arange(8).reshape(4,2)

In [22]:
array1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
array1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
a = np.array([[1,2,3],[4,5,6]])

In [25]:
b = np.array([[1,2,3],[4,5,6]])

In [27]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.stack((a,b))

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [33]:
np.stack((a,b), axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [34]:
np.stack((a,b), axis=1)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [37]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
a = np.arange(9)
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [42]:
a = np.arange(8)
np.split(a,2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

In [47]:
np.append(a,[[7,8,9,]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.append(a,[[7,8,9,]],axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [49]:
np.append(a,[[7,8,9,],[10,11,12]],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
a = np.array([[1, 2], [3, 4]])



In [54]:
np.insert(a,2,3,axis = 0)

array([[1, 2],
       [3, 4],
       [3, 3]])

In [55]:
x1=np.array([[1,2],[3,4],[7,8]])
n=np.insert(x1,2,[5,6],axis=0)
n

np.delete(n,3,axis=0)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
x1 = [1,2,3,4,5,6,7,8,4,2,5,6]
np.unique(x1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[5,6,7],[6,4,9]])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6  8 10]
 [10  9 15]]
[[-4 -4 -4]
 [-2  1 -3]]
[[ 5 12 21]
 [24 20 54]]
[[0.2        0.33333333 0.42857143]
 [0.66666667 1.25       0.66666667]]


In [59]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[5,6,7],[6,4,9]])

np.subtract(a,b)

array([[-4, -4, -4],
       [-2,  1, -3]])

In [60]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[5,6,7],[6,4,9]])

np.multiply(a,b)

array([[ 5, 12, 21],
       [24, 20, 54]])

In [61]:
np.divide(a,b)

array([[0.2       , 0.33333333, 0.42857143],
       [0.66666667, 1.25      , 0.66666667]])

In [63]:
array1 = np.array([3,5,6])
np.power(array1, 3)

array([ 27, 125, 216], dtype=int32)

In [64]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.percentile(array1, 50 , axis = 1)

array([2., 5., 8.])

In [65]:
np.mean

In [71]:
array1 = np.array([[1,2,3],[4,5,6]])
np.mean(array1, axis =0)

array([2.5, 3.5, 4.5])

In [73]:
np.median(array1, axis =0)

array([2.5, 3.5, 4.5])

In [74]:
np.std(array1, axis =0)

array([1.5, 1.5, 1.5])

## Pandas

In [76]:
import pandas as pd

In [77]:
a = np.array([10, 2 , 50 , 70])

In [85]:
s = pd.Series(a)

In [79]:
type(a)

numpy.ndarray

In [87]:
type(s)

pandas.core.series.Series

In [86]:
print(s)

0    10
1     2
2    50
3    70
dtype: int32


In [88]:
a = np.array([10, 2 , 50 , 70])
s = pd.Series(a, index=[10,20,30,40])

In [89]:
s

10    10
20     2
30    50
40    70
dtype: int32

In [101]:
dic1 = {ut1:'mhu',2:'kumaran',3:'india',4:'ukraine'}

In [104]:
s = pd.Series(dic1, index=[1,2,3,4])

In [105]:
s

1      muthu
2    kumaran
3      india
4    ukraine
dtype: object

In [106]:
pd.Series[1,2,3,4,5], index=[1,2,3,4,5])

SyntaxError: unmatched ')' (Temp/ipykernel_5044/3884049925.py, line 1)

In [107]:
list1 = [1,2,4,'name']
s = pd.Series(list1, index=[1,2,4,3])
print(s)


1       1
2       2
4       4
3    name
dtype: object


In [108]:
s[1:]

2       2
4       4
3    name
dtype: object

In [2]:
import pandas as pd
import numpy as np

## Creating a Dataframe

In [4]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## creating a df with list

In [7]:
list1 = list(range(5))
df = pd.DataFrame(list1)
df

0
0  0
1  1
2  2
3  3
4  4

In [14]:
list2 = [['python',2,4],['data',5,4],['science',8,4]]
df1 = pd.DataFrame(list2, columns=['subjects','number','col3'])
df1

subjects  number  col3
0   python       2     4
1     data       5     4
2  science       8     4

In [23]:
dic1 = {'Age':[15,25,35],'Salary':[4000,5000,6000]}
df2 = pd.DataFrame(dic1, index=[1,2,3])
df2

Age  Salary
1   15    4000
2   25    5000
3   35    6000

In [30]:
df2[['Age','Salary']]

Age  Salary
1   15    4000
2   25    5000
3   35    6000

In [31]:
df2.loc[:,['Age','Salary']]

Age  Salary
1   15    4000
2   25    5000
3   35    6000

In [41]:
dic2 = {'Age':[15,25,35],'Salary':[4000,5000,6000],'location':['chennai','hyderabad','bangalore']}
df3 = pd.DataFrame(dic2)
df3

Age  Salary   location
0   15    4000    chennai
1   25    5000  hyderabad
2   35    6000  bangalore

In [43]:
df3['address']=pd.Series([4,5,6])
df3

Age  Salary   location  address
0   15    4000    chennai        4
1   25    5000  hyderabad        5
2   35    6000  bangalore        6

In [50]:
df3['new_address']=df3['Age']+df3['address']
df3


Age  Salary   location  address  new_address
0   15    4000    chennai        4           19
1   25    5000  hyderabad        5           30
2   35    6000  bangalore        6           41

In [51]:
del df3['new_address']
df3

Age  Salary   location  address
0   15    4000    chennai        4
1   25    5000  hyderabad        5
2   35    6000  bangalore        6

In [52]:
df3.drop('Age', axis = 1, inplace=True)
df3

Salary   location  address
0    4000    chennai        4
1    5000  hyderabad        5
2    6000  bangalore        6

In [58]:
df3.drop(['Salary','location'], axis =1 , inplace=True)
df3

KeyError: "['Salary' 'location'] not found in axis"

In [59]:
df3

address
0        4
1        5
2        6

In [61]:
df3.drop([0,1], axis =0 , inplace=True)
df3

address
2        6

In [68]:
df1 = pd.DataFrame([['python',90],['science',80]],columns=['subjects','marks'])
df2 = pd.DataFrame([['java',50],['social',65]],columns=['subjects','marks'])
df3=  df1.append(df2)
df3

subjects  marks
0   python     90
1  science     80
0     java     50
1   social     65

In [69]:
df1 = pd.DataFrame([[10,'raj1',33],[20,'raj2',34],[30,'raj3',35]],columns=['slno','Name','Age'])
df1
df2 = pd.DataFrame([[40,'rk1',33],[50,'rk2',34],[60,'rk3',35]],columns=['slno','Name','Age'])
df3=df1.append(df2)
df3


slno  Name  Age
0    10  raj1   33
1    20  raj2   34
2    30  raj3   35
0    40   rk1   33
1    50   rk2   34
2    60   rk3   35

In [70]:
dic1 = {'Age':[25,26,25,23,30,29,23],
        'Name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],
        'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}
df = pd.DataFrame(dic1)
df                                        

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [71]:
df.head()

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20

In [73]:
df.tail(3)

Age   Name  Rating
4   30  Steve     3.2
5   29  Smith     4.6
6   23   Jack     3.8

In [74]:
df.T

0      1      2     3      4      5     6
Age       25     26     25    23     30     29    23
Name     Tom  James  Ricky   Vin  Steve  Smith  Jack
Rating  4.23   3.24   3.98  2.56    3.2    4.6   3.8

In [76]:
df.axes

[RangeIndex(start=0, stop=7, step=1),
 Index(['Age', 'Name', 'Rating'], dtype='object')]

In [77]:
df.dtypes

Age         int64
Name       object
Rating    float64
dtype: object

In [78]:
df.empty

False

In [79]:
df.shape

(7, 3)

In [81]:
df.sum()

Age                                  181
Name      TomJamesRickyVinSteveSmithJack
Rating                             25.61
dtype: object

In [83]:
df.sum()

Age                                  181
Name      TomJamesRickyVinSteveSmithJack
Rating                             25.61
dtype: object

In [84]:
df.sum(0)

Age                                  181
Name      TomJamesRickyVinSteveSmithJack
Rating                             25.61
dtype: object

In [86]:
import warnings
warnings.filterwarnings('ignore')

In [87]:
df.mean()

Age       25.857143
Rating     3.658571
dtype: float64

In [88]:
df.median()

Age       25.0
Rating     3.8
dtype: float64

In [90]:
df['Age'].mode() #most often repeated value

0    23
1    25
dtype: int64

In [91]:
df.std()

Age       2.734262
Rating    0.698628
dtype: float64

In [92]:
df.count()

Age       7
Name      7
Rating    7
dtype: int64

In [93]:
df['Age'].min()

23

In [94]:
df['Age'].max()

30

In [96]:
pd.DataFrame(df.describe())

Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0.698628
min    23.000000  2.560000
25%    24.000000  3.220000
50%    25.000000  3.800000
75%    27.500000  4.105000
max    30.000000  4.600000

In [95]:
df.describe()

Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0.698628
min    23.000000  2.560000
25%    24.000000  3.220000
50%    25.000000  3.800000
75%    27.500000  4.105000
max    30.000000  4.600000

In [5]:
dic = {'col1':[20,50,40,60,80],
       'col2':[80,60,40,20,55],
       'col3':[20,80,55,66,33]}
df1 = pd.DataFrame(dic)
df1

col1  col2  col3
0    20    80    20
1    50    60    80
2    40    40    55
3    60    20    66
4    80    55    33

In [103]:
df1.apply(np.mean)

col1    50.0
col2    51.0
col3    50.8
dtype: float64

In [107]:
df1.apply(lambda x:x.max() - x.min())

col1    60
col2    60
col3    60
dtype: int64

In [6]:
df2 = df1.rename(columns={'col1':'Columns1', 'col2': 'Columns2','col3':'columns3'},inplace=True)

In [11]:
df1

Columns1  Columns2  columns3
0        20        80        20
1        50        60        80
2        40        40        55
3        60        20        66
4        80        55        33

## Creating the DataFrame using random fn

In [14]:
df= pd.DataFrame(np.random.randn(5,2), index=[1,5,3,2,4],columns=['column1','column2'])
df

column1   column2
1 -1.726532  0.004228
5 -0.240392  1.071985
3 -0.664699 -1.036614
2 -0.133606  0.757695
4  0.736535  0.682238

In [13]:
np.random.randn(5)

array([ 0.5354559 , -0.71667271, -0.33425897,  0.13384826,  1.25562215])

## Sort the indexes

In [15]:
df.sort_index()

column1   column2
1 -1.726532  0.004228
2 -0.133606  0.757695
3 -0.664699 -1.036614
4  0.736535  0.682238
5 -0.240392  1.071985

In [16]:
df.sort_index(ascending=False)


column1   column2
5 -0.240392  1.071985
4  0.736535  0.682238
3 -0.664699 -1.036614
2 -0.133606  0.757695
1 -1.726532  0.004228



## Sorting columns



In [19]:
df.sort_index(axis = 1)

column1   column2
1 -1.726532  0.004228
5 -0.240392  1.071985
3 -0.664699 -1.036614
2 -0.133606  0.757695
4  0.736535  0.682238

In [20]:
df.sort_values(by = 'column1')

column1   column2
1 -1.726532  0.004228
3 -0.664699 -1.036614
5 -0.240392  1.071985
2 -0.133606  0.757695
4  0.736535  0.682238

In [21]:
dict3={'Age':[25,26,25,23,30,29,23],
       'Name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],
      'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}
df = pd.DataFrame(dict3)


In [22]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

## loc

In [27]:
df.loc[:2,['Age','Name']]

Age   Name
0   25    Tom
1   26  James
2   25  Ricky

## Changing the Index

In [28]:
df.index = ['a','b','c','d','e','f','g']
df

Age   Name  Rating
a   25    Tom    4.23
b   26  James    3.24
c   25  Ricky    3.98
d   23    Vin    2.56
e   30  Steve    3.20
f   29  Smith    4.60
g   23   Jack    3.80

In [36]:
df.loc['a':'e',['Age','Name']]

Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin
e   30  Steve

## iloc

In [38]:
df.iloc[:4,:2]

Age   Name
a   25    Tom
b   26  James
c   25  Ricky
d   23    Vin

In [40]:
df.iloc[:4,['Age','Name']] #you cant use column name as inputs, only integers as inputs

IndexError: .iloc requires numeric indexers, got ['Age' 'Name']

## Handling the missing data

In [44]:
df1= pd.DataFrame(np.random.randn(5,3), index=['a','c','e','f','h'],columns=['One','Two','Three'])
df1

One       Two     Three
a  0.165271 -0.800359  1.972048
c -0.464387  0.137213 -0.710037
e -1.023182  1.227908 -0.240439
f -0.988854 -1.454367 -0.937165
h  0.979993  1.328357  0.635298

In [46]:
df1 = df1.reindex(['a','b','c','d','e','f','g','h'])

In [47]:
df1

One       Two     Three
a  0.165271 -0.800359  1.972048
b       NaN       NaN       NaN
c -0.464387  0.137213 -0.710037
d       NaN       NaN       NaN
e -1.023182  1.227908 -0.240439
f -0.988854 -1.454367 -0.937165
g       NaN       NaN       NaN
h  0.979993  1.328357  0.635298

## Null and NOtnull functions

In [48]:
df1['Two'].isnull()

a    False
b     True
c    False
d     True
e    False
f    False
g     True
h    False
Name: Two, dtype: bool

In [49]:
df1['One'].notnull()

a     True
b    False
c     True
d    False
e     True
f     True
g    False
h     True
Name: One, dtype: bool

In [50]:
df1['Three'].isnull().sum()

3

In [51]:
df1.isnull().sum()

One      3
Two      3
Three    3
dtype: int64

## Filling missing data

In [52]:
df1['One'].fillna(0)

a    0.165271
b    0.000000
c   -0.464387
d    0.000000
e   -1.023182
f   -0.988854
g    0.000000
h    0.979993
Name: One, dtype: float64

In [54]:
df1.fillna(1, inplace=True)
df1

One       Two     Three
a  0.165271 -0.800359  1.972048
b  1.000000  1.000000  1.000000
c -0.464387  0.137213 -0.710037
d  1.000000  1.000000  1.000000
e -1.023182  1.227908 -0.240439
f -0.988854 -1.454367 -0.937165
g  1.000000  1.000000  1.000000
h  0.979993  1.328357  0.635298

In [56]:
df1.loc['d':'f']=pd.Series({'One':np.nan,'Two':np.nan, 'Three':np.nan})

In [57]:
df1

One       Two     Three
a  0.165271 -0.800359  1.972048
b  1.000000  1.000000  1.000000
c -0.464387  0.137213 -0.710037
d       NaN       NaN       NaN
e       NaN       NaN       NaN
f       NaN       NaN       NaN
g  1.000000  1.000000  1.000000
h  0.979993  1.328357  0.635298

In [58]:
df1.dropna()

One       Two     Three
a  0.165271 -0.800359  1.972048
b  1.000000  1.000000  1.000000
c -0.464387  0.137213 -0.710037
g  1.000000  1.000000  1.000000
h  0.979993  1.328357  0.635298

One       Two     Three
a -0.500787 -0.156912  0.633049
c  0.950706  1.212807  0.295835
e  0.192574  1.787871  0.446384
f -0.797071 -1.037475  1.154696
h -0.908836  1.136324  1.358180

In [73]:
dic1 = {'Age':[25,26,25,23,30,29,23],
        'Name':['Tom','James','Ricky','Vin','Steve','Smith','Jack'],
        'Rating':[4.23,3.24,3.98,2.56,3.20,4.60,3.80]}
df = pd.DataFrame(dic1)
df  

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [74]:
df

Age   Name  Rating
0   25    Tom    4.23
1   26  James    3.24
2   25  Ricky    3.98
3   23    Vin    2.56
4   30  Steve    3.20
5   29  Smith    4.60
6   23   Jack    3.80

In [75]:
df['Score'] =pd.Series([70,70,80,88,90,95,90])


In [76]:
df

Age   Name  Rating  Score
0   25    Tom    4.23     70
1   26  James    3.24     70
2   25  Ricky    3.98     80
3   23    Vin    2.56     88
4   30  Steve    3.20     90
5   29  Smith    4.60     95
6   23   Jack    3.80     90

In [77]:
df.groupby(['Age'])['Score'].sum()

Age
23    178
25    150
26     70
29     95
30     90
Name: Score, dtype: int64

In [81]:
df.groupby(['Age'])['Score','Rating'].mean().reset_index()

Age  Score  Rating
0   23   89.0   3.180
1   25   75.0   4.105
2   26   70.0   3.240
3   29   95.0   4.600
4   30   90.0   3.200

In [79]:
df.groupby(['Age'])['Score','Rating'].mean()

C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_2716/2790137818.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(['Age'])['Score','Rating'].mean()


Score  Rating
Age               
23    89.0   3.180
25    75.0   4.105
26    70.0   3.240
29    95.0   4.600
30    90.0   3.200

In [80]:
import warnings
warnings.filterwarnings('ignore')

###  Multiple aggregations

In [82]:
df.groupby(['Age'])['Score','Rating'].agg([np.mean,np.median]).reset_index()

Age Score        Rating       
       mean median   mean median
0  23  89.0   89.0  3.180  3.180
1  25  75.0   75.0  4.105  4.105
2  26  70.0   70.0  3.240  3.240
3  29  95.0   95.0  4.600  4.600
4  30  90.0   90.0  3.200  3.200

### Merge - > join

In [85]:
df_left = {'Name':["alex",'amy','allen','alice','ayoung'],
        'id':[1,2,3,4,5],
          'subject_id':['sub1','sub2','sub4','sub6','sub5']}
df_left = pd.DataFrame(df_left)
df_left


df_right = {'Name':["billy",'brian','bran','bryce','betty'],
        'id':[1,2,3,4,5],
          'subject_id':['sub2','sub4','sub3','sub6','sub5']}
df_right = pd.DataFrame(df_right)
df_right

Name  id subject_id
0    alex   1       sub1
1     amy   2       sub2
2   allen   3       sub4
3   alice   4       sub6
4  ayoung   5       sub5

In [87]:
df_right = {'Name':["billy",'brian','bran','bryce','betty'],
        'id':[1,2,3,4,5],
          'subject_id':['sub2','sub4','sub3','sub6','sub5']}
df_right = pd.DataFrame(df_right)
df_right

Name  id subject_id
0  billy   1       sub2
1  brian   2       sub4
2   bran   3       sub3
3  bryce   4       sub6
4  betty   5       sub5

### merge with one key

In [92]:
pd.merge(df_left,df_right,on=['id','subject_id'])

Name_x  id subject_id Name_y
0   alice   4       sub6  bryce
1  ayoung   5       sub5  betty

In [88]:
pd.merge(df_left,df_right,on='id')

Name_x  id subject_id_x Name_y subject_id_y
0    alex   1         sub1  billy         sub2
1     amy   2         sub2  brian         sub4
2   allen   3         sub4   bran         sub3
3   alice   4         sub6  bryce         sub6
4  ayoung   5         sub5  betty         sub5

## merger operation using 'how' -- > left outer join

In [90]:
df_left.merge(df_right, on='subject_id', how = 'left')

Name_x  id_x subject_id Name_y  id_y
0    alex     1       sub1    NaN   NaN
1     amy     2       sub2  billy   1.0
2   allen     3       sub4  brian   2.0
3   alice     4       sub6  bryce   4.0
4  ayoung     5       sub5  betty   5.0

### Concat

In [94]:
pd.concat([df_left,df_right],axis=1) #column wise operation

Name  id subject_id   Name  id subject_id
0    alex   1       sub1  billy   1       sub2
1     amy   2       sub2  brian   2       sub4
2   allen   3       sub4   bran   3       sub3
3   alice   4       sub6  bryce   4       sub6
4  ayoung   5       sub5  betty   5       sub5

In [96]:
pd.concat([df_left,df_right]) #row wise operation

Name  id subject_id
0    alex   1       sub1
1     amy   2       sub2
2   allen   3       sub4
3   alice   4       sub6
4  ayoung   5       sub5
0   billy   1       sub2
1   brian   2       sub4
2    bran   3       sub3
3   bryce   4       sub6
4   betty   5       sub5

In [97]:
pd.concat([df_left,df_right],ignore_index=True)

Name  id subject_id
0    alex   1       sub1
1     amy   2       sub2
2   allen   3       sub4
3   alice   4       sub6
4  ayoung   5       sub5
5   billy   1       sub2
6   brian   2       sub4
7    bran   3       sub3
8   bryce   4       sub6
9   betty   5       sub5

## Append operation to demonstrate Concat

In [98]:
df_left.append(df_right, ignore_index=True)

Name  id subject_id
0    alex   1       sub1
1     amy   2       sub2
2   allen   3       sub4
3   alice   4       sub6
4  ayoung   5       sub5
5   billy   1       sub2
6   brian   2       sub4
7    bran   3       sub3
8   bryce   4       sub6
9   betty   5       sub5