In [1]:
import numpy as np

In [21]:
array1 = np.array([1,2,3,4])

In [22]:
array1.shape

(4,)

In [4]:
array1.ndim

1

In [5]:
array1 = np.array([[1,2,3],[4,5,6]])

In [6]:
array1.shape

(2, 3)

In [7]:
array1.ndim

2

In [13]:
array1= np.array([[1,2,3,4],[8,4,5,6]],dtype=float)

In [17]:
array1

array([[1., 2., 3., 4.],
       [8., 4., 5., 6.]])

In [19]:
a1 = array1.reshape(4,2)
a1

array([[1., 2.],
       [3., 4.],
       [8., 4.],
       [5., 6.]])

In [20]:
a1.shape

(4, 2)

In [28]:
array_zero= np.zeros([4,4])
array_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
array_ones = np.ones([4,5])

In [32]:
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
array_ones = np.ones([4,6],dtype=int)

In [34]:
array_ones

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [38]:
x1 = ([3,4],[5,6],[7,8])
x2 = np.asarray(x1,dtype = float)

In [39]:
x2

array([[3., 4.],
       [5., 6.],
       [7., 8.]])

In [40]:
type(x1)

tuple

In [41]:
type(x2)

numpy.ndarray

In [60]:
a1 = np.linspace(10,20,4,dtype=int)

In [61]:
a1

array([10, 13, 16, 20])

In [55]:
a1 = np.linspace(100,200,8)

In [56]:
a1

array([100.        , 114.28571429, 128.57142857, 142.85714286,
       157.14285714, 171.42857143, 185.71428571, 200.        ])

In [58]:
list1=np.arange(20)
array1=list1[10: 16 : 1]
list1[array1]

array([10, 11, 12, 13, 14, 15])

In [59]:
len(list1)

20

In [65]:
a = np.array([[1,2],[3,4],[5,6]])
b = a[[0,1,2],[1,1,1]]
b

array([2, 4, 6])

In [67]:
a= np.array([[1,2],[3,4],[5,6]])

In [69]:
b = a[[0,1,2],[0,0,0]]


In [71]:
print(b)

[1 3 5]


In [72]:
b

array([1, 3, 5])

In [75]:
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a1[1:,1:]
b

array([[ 6,  7,  8],
       [10, 11, 12]])

In [82]:
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a1[0:3,0:3]
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [83]:
a1.shape

(1, 3, 4)

In [84]:
a1.ndim

3

In [90]:
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a1[ :3 , :4]
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
a1[0:4,[1,2,3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [95]:
a1[0:2,[0,2,3]]

array([[1, 3, 4],
       [5, 7, 8]])

In [97]:
a1[a1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [98]:
a1[a1<5]

array([1, 2, 3, 4])

In [99]:
a = np.array([1,2,3,np.nan,5,np.nan])
a

array([ 1.,  2.,  3., nan,  5., nan])

In [102]:
np.isnan(a)

array([False, False, False,  True, False,  True])

In [103]:
a[np.isnan(a)]

array([nan, nan])

In [104]:
a[~np.isnan(a)]  #not null values how to fetch using tilde

array([1., 2., 3., 5.])

In [107]:
a = np.array([[[1,2,3],[4,5,6]],[7,8,9]])
b = np.array([4,5,6])
c =  a*b
c

C:\Users\MUTHUK~1\AppData\Local\Temp/ipykernel_1936/48375321.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[[1,2,3],[4,5,6]],[7,8,9]])


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [108]:
a.shape

(2,)

In [109]:
b.shape

(3,)

In [111]:
a.ndim

1

In [112]:
b.ndim

1

In [119]:
C = np.array([7, 5, 6, 3]).reshape(2, 2)
D = np.array([2, 1, 4, 5, 1, 2]).reshape(2, 3)
print(C)
print(D)

[[7 5]
 [6 3]]
[[2 1 4]
 [5 1 2]]


In [115]:
a = C*D

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [122]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([4,5,6])
c =  a*b
c

array([[ 4, 10, 18],
       [16, 25, 36],
       [28, 40, 54]])

In [123]:
c.T

array([[ 4, 16, 28],
       [10, 25, 40],
       [18, 36, 54]])

In [124]:
array1=np.array([1,2,3,4,5,6]).reshape(3,2)
array1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
array1.flatten()

array([1, 2, 3, 4, 5, 6])

In [128]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.concatenate(a,b)
c

TypeError: only integer scalar arrays can be converted to a scalar index

In [137]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.concatenate((a,b))
c

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [130]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.stack((a,b))
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [138]:
np.stack((a,b),axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [157]:
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]]])

In [142]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [143]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [144]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
a = np.arange(9)
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [149]:
a = np.arange(6)
np.split(a,6)

[array([0]), array([1]), array([2]), array([3]), array([4]), array([5])]

In [152]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.append(a,b)
c

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [154]:
np.append(a,b,axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [155]:
np.append(a,b,axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [4]:
x=([[1,2,3],[4,5,6]])

In [5]:
x

[[1, 2, 3], [4, 5, 6]]

In [6]:
np.insert(x,1,10,axis=0)

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 4,  5,  6]])

In [16]:
np.insert(x,2,[10,20,30],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [24]:
np.insert(x,2,[[10,20],[28,34]],axis=1)             #inserting values in frst index

array([[ 1,  2, 10, 28,  3],
       [ 4,  5, 20, 34,  6]])

In [25]:
x

[[1, 2, 3], [4, 5, 6]]

In [26]:
np.delete(x,2,axis=1) 

array([[1, 2],
       [4, 5]])

In [30]:
x

[[1, 2, 3], [4, 5, 6]]

In [32]:
np.delete(x,0,axis=0)   #axis = 0 takes whole array as 0th index not a single value

array([[4, 5, 6]])

In [33]:
np.delete(x,1,axis=0)   #axis = 0 takes whole array as 0th index not a single value

array([[1, 2, 3]])

In [36]:
x = np.array([1,2,2,3,3,4,4,5,0,6,7,8,8,9])

In [38]:
np.unique(x)                            #unique values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[4,5,6],[7,8,9]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 5  7  9]
 [11 13 15]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [28 40 54]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]]


In [40]:
a =np.array([[1,2,3],[4,5,6]])          #power
np.power(a,3) 

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [45]:
a =np.array([[1,2,3],[4,5,6]])
np.percentile(a,50,axis=1)

array([2., 5.])

In [44]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])      #percentile
np.percentile(a,50,axis=0)

array([4., 5., 6.])

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.mean(a,axis=0)

array([4., 5., 6.])

In [52]:
np.mean(a,axis=1)

array([2., 5., 8.])

In [53]:
np.median(a,axis=0)

array([4., 5., 6.])

In [54]:
np.median(a,axis=1)

array([2., 5., 8.])

In [55]:
np.std(a,axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [56]:
np.std(a,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

###  Pandas

In [2]:
import pandas as pd

In [58]:
a = np.array([0,20,30,40])
s = pd.Series(a)
s

0     0
1    20
2    30
3    40
dtype: int32

In [59]:
type(s)

pandas.core.series.Series

In [60]:
a = np.array([0,20,30,40])
s = pd.Series(a,index=[10,20,30,40])
s

10     0
20    20
30    30
40    40
dtype: int32

In [63]:
dict1= {1:'muthu',2:'kumaran',3:'india'}
s = pd.Series(dict1,index=[1,2,3])
s

1      muthu
2    kumaran
3      india
dtype: object

In [64]:
s[1]

'muthu'

In [66]:
dict1= {1:'muthu',2:'kumaran',3:'india'}
s = pd.Series(dict1,index=[2,3])
s

2    kumaran
3      india
dtype: object

In [72]:
s[0:]

2    kumaran
3      india
dtype: object

###  Creating a Dataframe

In [4]:
df = pd.DataFrame()

In [5]:
print(df)

Empty DataFrame
Columns: []
Index: []


In [11]:
a= list(range(5))

In [13]:
df = pd.DataFrame(a)

In [14]:
df

0
0  0
1  1
2  2
3  3
4  4

In [25]:
list2=[['abc','sima',1],['gef','uma',2],['hij','kuma',3]]

In [26]:
df = pd.DataFrame(list2)

In [27]:
df

0     1  2
0  abc  sima  1
1  gef   uma  2
2  hij  kuma  3

In [29]:
df = pd.DataFrame(list2,columns=['alpabhets','Names','numbers'])

In [30]:
df

alpabhets Names  numbers
0       abc  sima        1
1       gef   uma        2
2       hij  kuma        3

In [31]:
dic1={'MI':[1,2,3],'CSK':[4,5,6],'RCB':[7,8,9]}
df=pd.DataFrame(dic1, index=[1,2,3])
df

MI  CSK  RCB
1   1    4    7
2   2    5    8
3   3    6    9

In [39]:
df[['CSK','MI']]

CSK  MI
1    4   1
2    5   2
3    6   3

In [40]:
df[['CSK','MI','RCB']]   #like this

CSK  MI  RCB
1    4   1    7
2    5   2    8
3    6   3    9

In [41]:
list1=['CSK','MI','RCB']  #either pass into a list and 

In [44]:
df[list1]


CSK  MI  RCB
1    4   1    7
2    5   2    8
3    6   3    9

In [45]:
df

MI  CSK  RCB
1   1    4    7
2   2    5    8
3   3    6    9

In [63]:
df = df.rename(columns={"MI":'MUMBAI','CSK':'CHENNAI','RCB':'Bangalore'})   # renaming columns in a dictionary

In [64]:
df

MUMBAI  CHENNAI  Bangalore
1       1        4          7
2       2        5          8
3       3        6          9

In [66]:
df[:2]["CHENNAI"]

1    4
2    5
Name: CHENNAI, dtype: int64

In [67]:
df.iloc[0:2 , 0:2]

MUMBAI  CHENNAI
1       1        4
2       2        5

In [69]:
df.loc[:,['MUMBAI','CHENNAI']]

MUMBAI  CHENNAI
1       1        4
2       2        5
3       3        6

In [75]:
dict1={'Name':['muthu','kumaran','priya','hadoop'],
               'Age':[30,40,50,60],
               'Salary':[200,300,400,500]} 
df =pd.DataFrame(dict1)
df



Name  Age  Salary
0    muthu   30     200
1  kumaran   40     300
2    priya   50     400
3   hadoop   60     500

In [80]:
df['School'] = pd.Series(['CSV','RMK','RMV','LMV'])
df

Name  Age  Salary School
0    muthu   30     200    CSV
1  kumaran   40     300    RMK
2    priya   50     400    RMV
3   hadoop   60     500    LMV

In [81]:
df['Add']=df['Age']+df['Salary']

In [82]:
df

Name  Age  Salary School  Add
0    muthu   30     200    CSV  230
1  kumaran   40     300    RMK  340
2    priya   50     400    RMV  450
3   hadoop   60     500    LMV  560

In [83]:
del df['Add']
df

Name  Age  Salary School
0    muthu   30     200    CSV
1  kumaran   40     300    RMK
2    priya   50     400    RMV
3   hadoop   60     500    LMV

In [1]:
a =list(range(10))

In [2]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
a[3]=18

In [4]:
a

[0, 1, 2, 18, 4, 5, 6, 7, 8, 9]

In [6]:
a[2:7]

[2, 18, 4, 5, 6]

In [17]:
a[-7]

18

In [19]:
a[3:7]

[18, 4, 5, 6]

In [29]:
a[-5:-2]

[5, 6, 7]

In [30]:
a[-9:-1]

[1, 2, 18, 4, 5, 6, 7, 8]

In [31]:
a[-7:-3]

[18, 4, 5, 6]

In [33]:
s = 'this is a string'
print('-'.join(s))

t-h-i-s- -i-s- -a- -s-t-r-i-n-g


In [34]:
s.split(' ')

['this', 'is', 'a', 'string']

In [38]:
s[-8:-2]

'a stri'

In [39]:
s[-6:]

'string'

In [40]:
s[3]='r'

TypeError: 'str' object does not support item assignment

In [41]:
set1={1,2,3,4,5}

In [42]:
set1[2]

TypeError: 'set' object is not subscriptable

In [51]:
set1 = {111,111,2223,2223,34,34,556,5567}

In [52]:
set1

{34, 111, 556, 2223, 5567}

In [54]:
dict1={1:'mutu', 2:'kum' , 3:'gui'}

In [61]:
dict1['kum']

KeyError: 'kum'

In [56]:
dict1[1]

'mutu'

In [57]:
dict1[1]='all'

In [58]:
dict1

{1: 'all', 2: 'kum', 3: 'gui'}

In [59]:
dict1[2]=3

In [60]:
dict1

{1: 'all', 2: 3, 3: 'gui'}

In [62]:
float(10)

10.0

In [63]:
int(10.5)

10

In [66]:
str(10)

'10'

In [67]:
 str(20)

'20'

In [70]:
str(10.678)

'10.678'

In [76]:
list1=[1,2,3,4,5,6,7,7]

In [82]:
a = list1
a

[1, 2, 3, 4, 5, 6, 7, 7]

In [83]:
tuple(a)

(1, 2, 3, 4, 5, 6, 7, 7)

In [84]:
list("LIST")

['L', 'I', 'S', 'T']

In [89]:
dict([['name','john'],[10,50]])


{'name': 'john', 10: 50}

In [92]:
int1=12
float1=14.5
c=int1+float1

print('Datatype of variable int1 is:', type(int1))
print('Datatype of variable float1 is:', type(float1))
print('Datatype of variable c is:', type(c))
c

Datatype of variable int1 is: <class 'int'>
Datatype of variable float1 is: <class 'float'>
Datatype of variable c is: <class 'float'>


26.5

In [93]:
int1=12
float1='14.5'
c=int1+ float1

print('Datatype of variable int1 is:', type(int1))
print('Datatype of variable float1 is:', type(float1))
print('Datatype of variable c is:', type(c))
c

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [95]:
int1=12
float1=int('14.5')
c=int1+ float1

print('Datatype of variable int1 is:', type(int1))
print('Datatype of variable float1 is:', type(float1))
print('Datatype of variable c is:', type(c))
c

ValueError: invalid literal for int() with base 10: '14.5'

In [96]:
int1=12
float1=float('14.5')
c=int1+ float1

print('Datatype of variable int1 is:', type(int1))
print('Datatype of variable float1 is:', type(float1))
print('Datatype of variable c is:', type(c))
c

Datatype of variable int1 is: <class 'int'>
Datatype of variable float1 is: <class 'float'>
Datatype of variable c is: <class 'float'>


26.5

In [102]:
num = str(input('enter the number:'))

enter the number:8


In [103]:
num

'8'

In [111]:
a= eval('23 + 5')
a

28

NameError: name 'add' is not defined

In [117]:
x = 13
y = 6

x//y

2

In [118]:
round(3.5)

4

In [119]:
x = True
y = False
x and y

False

In [120]:
x or y

True

In [121]:
x or y 

True

In [122]:
not x

False

In [127]:
x2 = 15
y2= 15

In [128]:
id(x),id(y)

(1589506763504, 1589506763504)

In [129]:
id(x2),id(y2)

(1589506763504, 1589506763504)

In [ ]:
x = [1,2,3 ]

In [1]:
def fn1():
    """hello this is practice"""
    return True

In [2]:
fn1()

True

In [3]:
fn1.__doc__

'hello this is practice'

In [14]:
list2 = [20,5.3,25,7.5]
print([i for i in list2 if i >= 20])
print([a for a in list2 if a <= 20])


[20, 25]
[20, 5.3, 7.5]


In [13]:
a = 'this is a string'
a = a.split(' ')
print(a)

['this', 'is', 'a', 'string']


In [19]:
a = 'this is a string'
a = "-".join(a)
print(a)

t-h-i-s- -i-s- -a- -s-t-r-i-n-g


In [3]:
digit = (1+2+4 
+5+6)
print(digit)

18


In [ ]:
# print('hello this is muthu')
# print('i am a python specialist')
# print('I am a good programmer')

In [ ]:
# print('wat r u doin')
# print('I wont work')

In [4]:
"""hello
hw r u 
ia m good
r u sure"""

'hello\nhw r u \nia m good\nr u sure'

In [8]:
import math

In [10]:
factorial(5)

NameError: name 'factorial' is not defined

In [1]:
keyword.kwlist()

NameError: name 'keyword' is not defined

In [2]:
import keyword

In [ ]:
def addition():
    num = int(input("Enter a number to find the factorial: "))
    result = factorial(num)
    print("The factorial of", num, "is", result)
return addition

In [ ]:
addition()

In [11]:
n = eval(input("enter the integer:"))
for i in range(1,n+1):
    print(i,end="")


enter the integer:10
12345678910

In [4]:
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [5]:
var_q = ('jfoidfi')
print(var_q)

jfoidfi


In [13]:
digi = 2 + 2 + 3 + 4 + \
5 + 6 + 7 \
+ 8
print(digi)

37


# 

### 

In [14]:
a=1;b=2;c=3
print(a+b-c)

0


In [20]:
list(range(10,60,end=","))

TypeError: range() takes no keyword arguments

In [21]:
list(range(12,89))

[12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88]

In [22]:
list(range(23,78))

[23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77]

In [23]:
for i in rane(1,8)

SyntaxError: invalid syntax (Temp/ipykernel_5632/1823379532.py, line 1)

In [26]:
for i in range(1,8):
    print (i)
    if (i == 6):
        break

1
2
3
4
5
6


In [27]:
for i in range(1,8): print(i)

1
2
3
4
5
6
7


In [35]:
def funx():
    """helloedfg"""
    print('hello122')

In [36]:
print(funx.__doc__)

helloedfg


In [38]:
print(funx.__doc__)

helloedfg


In [39]:
from my_package import test_package

In [44]:
my_package_var = test_package.b
print(my_package_var)

51


In [62]:
list1 =[1,4,3]

In [49]:
print(list1)

[1, 'liili', 3]


## list comprehension

In [52]:
[i for i in list1 if i == 'liili']

['liili']

In [58]:
i2 = [i**2 for i in list1 if i%2!= 0]
print(list(i2))

[1, 9]


In [65]:
[a**2 for a in list1 if a==4]

[16]

In [74]:
[a**3 for a in range(30) if a%2==0]


[0,
 8,
 64,
 216,
 512,
 1000,
 1728,
 2744,
 4096,
 5832,
 8000,
 10648,
 13824,
 17576,
 21952]

In [75]:
list(range(2,20,5))

[2, 7, 12, 17]

In [77]:
list(range(3,18,3))

[3, 6, 9, 12, 15]

In [78]:
list(range(4,20,6))

[4, 10, 16]

In [87]:
list2= [1,3,4,5,6,3,4,3,5,34,335,33]

In [82]:
list2[8]

5

In [83]:
list2[3:8]

[5, 6, 3, 4, 3]

In [88]:
list2[-6:-1]

[4, 3, 5, 34, 335]

In [91]:
t= (2,3,4,5,6,7,7)

In [92]:
t2[2]=4

TypeError: 'tuple' object does not support item assignment

In [94]:
t[2:7]

(4, 5, 6, 7, 7)

In [95]:
l=[2,3,4,5,6,7]

In [96]:
l[2]=78

In [97]:
print(l)

[2, 3, 78, 5, 6, 7]


In [98]:
s = 'hello muthu'

In [99]:
type(s)

str

In [100]:
s[2:6]

'llo '

In [101]:
s[-5:-1]

'muth'

In [102]:
s[2]='f'

TypeError: 'str' object does not support item assignment

In [110]:
set1={1,2,3,4,5,6,7,7,8,8,9,0,'mut1','mut1'}

In [108]:
set1[4]

TypeError: 'set' object is not subscriptable

set1

In [111]:
set1

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'mut1'}

In [112]:
dic1={1:'a',2:'b',3:'c'}

In [113]:
dic1[1]

'a'

In [114]:
dic1[1]='muthu'

In [115]:
dic1

{1: 'muthu', 2: 'b', 3: 'c'}

In [116]:
dic1[2]='hello'

In [117]:
dic1

{1: 'muthu', 2: 'hello', 3: 'c'}